import './globals.css';
import './output.css';
import Navbar from '@/components/reusable/Navbar/Navbar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Learn with Sumit</title>
      </head>

      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
